const data = [
  {
    id: "1",
    name: "Dr. Brian Wolfe",
    specialisation: "Therapist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Brian Wolfe is a dedicated therapist with a passion for helping individuals navigate life's challenges. He creates a safe and supportive environment for his patients to explore their feelings and develop coping strategies.",
    email: "brian.wolfe@example.com",
    contact_no: "0096278954321",
    stars: 5,
  },
  {
    id: "2",
    name: "Dr. Selena Kane",
    specialisation: "Therapist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Selena Kane is a compassionate therapist committed to empowering her patients to achieve emotional well-being. She believes in the importance of self-reflection and personal growth in the therapeutic process.",
    email: "selena.kane@example.com",
    contact_no: "0096278123456",
    stars: 5,
  },
  {
    id: "3",
    name: "Kate Williams",
    specialisation: "Personal Trainer",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Kate Williams is a certified personal trainer dedicated to helping clients achieve their fitness goals. With a focus on customized workout plans and nutritional guidance, she empowers individuals to lead a healthier lifestyle.",
    email: "kate.williams@example.com",
    contact_no: "0096278234567",
    stars: 5,
  },
  {
    id: "4",
    name: "Dr. Samantha Kalra",
    specialisation: "Personal Trainer",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Samantha Kalra is a fitness enthusiast and personal trainer known for her motivating and innovative training techniques. She believes in the importance of a balanced approach to fitness and nutrition for overall well-being.",
    email: "samantha.kalra@example.com",
    contact_no: "0096278345678",
    stars: 4,
  },
  {
    id: "5",
    name: "Dr. David Bing",
    specialisation: "Nutritionist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. David Bing is a skilled nutritionist dedicated to promoting healthy eating habits and lifestyle choices. He emphasizes the importance of personalized nutrition plans tailored to individual needs and goals.",
    email: "david.bing@example.com",
    contact_no: "0096278456789",
    stars: 4,
  },
  {
    id: "6",
    name: "Dr. Sharon Odell",
    specialisation: "Nutritionist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Sharon Odell is a dedicated nutritionist with a passion for promoting well-balanced diets and healthy lifestyles. She believes in empowering her clients with knowledge to make informed choices about their nutrition.",
    email: "sharon.odell@example.com",
    contact_no: "0096278567890",
    stars: 4,
  },
  {
    id: "7",
    name: "Dr. Ethan Hudson",
    specialisation: "Endocrinologist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "provides comprehensive care to his patients and is dedicated to improving their quality of life through effective treatments.",
    email: "ethan.hudson@example.com",
    contact_no: "0096278678901",
    stars: 4,
  },
  {
    id: "8",
    name: "Dr. Maya Patel",
    specialisation: "Endocrinologist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Maya Patel is a compassionate endocrinologist known for her expertise in managing endocrine disorders. She focuses on personalized treatment plans and strives to enhance the overall well-being of her patients.",
    email: "maya.patel@example.com",
    contact_no: "0096278789012",
    stars: 5,
  },
  {
    id: "9",
    name: "Dr. Alex Turner",
    specialisation: "Therapist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Alex Turner is a dedicated therapist with a focus on cognitive-behavioral therapy. He is passionate about helping individuals overcome anxiety, depression, and other mental health challenges to lead fulfilling lives.",
    email: "alex.turner@example.com",
    contact_no: "0096278890123",
    stars: 5,
  },
  {
    id: "10",
    name: "Dr. Olivia White",
    specialisation: "Endocrinologist",
    img: "https://cdn-icons-png.flaticon.com/128/552/552848.png",
    bio: "Dr. Olivia White is a skilled endocrinologist specializing in diabetes management and thyroid disorders. She is dedicated to providing exceptional care to her patients and helping them achieve optimal health.",
    email: "olivia.white@example.com",
    contact_no: "0096278123456",
    stars: 4,
  },
];

export default data;
